Appointment details form
HKanwal/kapstone pull request #173
Opened 2023-03-09 03:07 UTC by rachelj1098

2023-03-25 15:38 UTC, HKanwal requested changes

2023-03-25 15:38 UTC, HKanwal commented on src/next-app/pages/appointment-details.tsx
> +    const appointment = await axios.get(`${apiUrl}/shops/appointments/${id}`, {
This request doesn't work (it gives a 404) when using shop owner JWT instead of customer JWT. Let's talk to Himanshu about this in meeting today.

2023-03-25 18:25 UTC, HKanwal commented on src/next-app/pages/appointment-details.tsx
> +    const appointment = await axios.get(`${apiUrl}/shops/appointments/${id}`, {
According to the meeting discussion, it looks like the problem is not with this request, but with the vehicles request.

2023-03-26 20:56 UTC, tevisdoe approved these changes
Approving this because it looks good to me. Make sure to swap back to the non-hardcoded ID, as I said.

2023-03-26 20:56 UTC, tevisdoe commented on src/next-app/pages/appointment-details.tsx
> +  const id = 1;
Make sure to change this hardcoded id before this gets merged.

2023-03-26 21:19 UTC, HKanwal requested changes

2023-03-26 21:19 UTC, HKanwal commented on src/next-app/pages/appointment-details.tsx
> +      ? await axios.get(`${apiUrl}/vehicles/vehicles/${appointment.data.vehicle}/`, {
This still doesn't work. `appointment.data.vehicle` appears to be being used as a number but it is actually the following object: 
![image](https://user-images.githubusercontent.com/18541493/227805176-5ca22ef6-4886-48f3-a37f-1f29eb033e97.png)

2023-03-26 22:38 UTC, HKanwal approved these changes
Looks good. Just one type in URL below.

2023-03-26 22:38 UTC, HKanwal commented on src/next-app/pages/appointment-details.tsx
> +          `${apiUrl}/shops/apponitments/${id}/`,
Small typo here.

2023-03-26 23:07 UTC, merged