Setup CI
HKanwal/kapstone pull request #34
Opened 2022-10-11 23:39 UTC by HKanwal

See #17

2022-10-12 01:45 UTC, aggarwal-h requested changes

2022-10-12 02:47 UTC, HKanwal commented on .github/workflows/main.yml
> +          npm install
Why is it necessary to use yarn on the runner?

2022-10-12 03:08 UTC, aggarwal-h commented on .github/workflows/main.yml
> +          npm install
_npm_ can sometimes mess up builds if there is no `package-lock.json` file present. It does not fully support `yarn.lock`.

It's just recommended to use _yarn_ if we have a `yarn.lock` file.

2022-10-14 09:04 UTC, HKanwal commented on .github/workflows/main.yml
> +          npm install
Changed to yarn and added caching.

2022-10-15 03:03 UTC, aggarwal-h approved these changes

2022-10-15 07:04 UTC, merged